#     /$$$$$$$$           /$$       /$$       /$$                 /$$$$$$$                                    /$$                 /$$      /$$                     /$$   /$$                        
#    |_____ $$           | $$      | $$      |__/                | $$__  $$                                  |__/                | $$$    /$$$                    |__/  | $$                        
#         /$$/   /$$$$$$ | $$$$$$$ | $$$$$$$  /$$ /$$   /$$      | $$  \ $$  /$$$$$$  /$$$$$$/$$$$   /$$$$$$  /$$ /$$$$$$$       | $$$$  /$$$$  /$$$$$$  /$$$$$$$  /$$ /$$$$$$    /$$$$$$   /$$$$$$ 
#        /$$/   |____  $$| $$__  $$| $$__  $$| $$|  $$ /$$/      | $$  | $$ /$$__  $$| $$_  $$_  $$ |____  $$| $$| $$__  $$      | $$ $$/$$ $$ /$$__  $$| $$__  $$| $$|_  $$_/   /$$__  $$ /$$__  $$
#       /$$/     /$$$$$$$| $$  \ $$| $$  \ $$| $$ \  $$$$/       | $$  | $$| $$  \ $$| $$ \ $$ \ $$  /$$$$$$$| $$| $$  \ $$      | $$  $$$| $$| $$  \ $$| $$  \ $$| $$  | $$    | $$  \ $$| $$  \__/
#      /$$/     /$$__  $$| $$  | $$| $$  | $$| $$  >$$  $$       | $$  | $$| $$  | $$| $$ | $$ | $$ /$$__  $$| $$| $$  | $$      | $$\  $ | $$| $$  | $$| $$  | $$| $$  | $$ /$$| $$  | $$| $$      
#     /$$$$$$$$|  $$$$$$$| $$$$$$$/| $$$$$$$/| $$ /$$/\  $$      | $$$$$$$/|  $$$$$$/| $$ | $$ | $$|  $$$$$$$| $$| $$  | $$      | $$ \/  | $$|  $$$$$$/| $$  | $$| $$  |  $$$$/|  $$$$$$/| $$      
#    |________/ \_______/|_______/ |_______/ |__/|__/  \__/      |_______/  \______/ |__/ |__/ |__/ \_______/|__/|__/  |__/      |__/     |__/ \______/ |__/  |__/|__/   \___/   \______/ |__/      
#                                                                                                                                                                                                   
#                                                                                                                                                                                  by maj0r
#                                                                                                                                                                                                   
# Acesse o projeto em https://github.com/lmaj0r/zabbix-domain-monitor
#
# UserParameters para consulta WHOIS de domínios.
#
# Formato usado pelo template:
#   domain.<atributo>[dominio]
#
# Exemplos:
#   domain.expira[empresa.com.br]
#   domain.status[empresa.com.br]
#   domain.dns1[empresa.com.br]
#
# Script chamado internamente:
#   /etc/zabbix/scripts/zabbix_domain_monitor.sh <atributo> <dominio>

UserParameter=domain.nome[*],/etc/zabbix/scripts/zabbix_domain_monitor.sh nome "$1"
UserParameter=domain.status[*],/etc/zabbix/scripts/zabbix_domain_monitor.sh status "$1"
UserParameter=domain.dono[*],/etc/zabbix/scripts/zabbix_domain_monitor.sh dono "$1"
UserParameter=domain.donocnpj[*],/etc/zabbix/scripts/zabbix_domain_monitor.sh donocnpj "$1"
UserParameter=domain.dononome[*],/etc/zabbix/scripts/zabbix_domain_monitor.sh dononome "$1"
UserParameter=domain.pais[*],/etc/zabbix/scripts/zabbix_domain_monitor.sh pais "$1"
UserParameter=domain.donoregistro[*],/etc/zabbix/scripts/zabbix_domain_monitor.sh donoregistro "$1"
UserParameter=domain.suporteregistro[*],/etc/zabbix/scripts/zabbix_domain_monitor.sh suporteregistro "$1"
UserParameter=domain.dns1[*],/etc/zabbix/scripts/zabbix_domain_monitor.sh dns1 "$1"
UserParameter=domain.dns2[*],/etc/zabbix/scripts/zabbix_domain_monitor.sh dns2 "$1"
UserParameter=domain.dns3[*],/etc/zabbix/scripts/zabbix_domain_monitor.sh dns3 "$1"
UserParameter=domain.dns4[*],/etc/zabbix/scripts/zabbix_domain_monitor.sh dns4 "$1"
UserParameter=domain.criado[*],/etc/zabbix/scripts/zabbix_domain_monitor.sh criado "$1"
UserParameter=domain.criadonumero[*],/etc/zabbix/scripts/zabbix_domain_monitor.sh criadonumero "$1"
UserParameter=domain.alterado[*],/etc/zabbix/scripts/zabbix_domain_monitor.sh alterado "$1"
UserParameter=domain.expira[*],/etc/zabbix/scripts/zabbix_domain_monitor.sh expira "$1"
