# zabbix-domain-monitor
# UserParameters para consulta WHOIS de domínios.
#
# Formato usado pelo template:
#   domain.<atributo>[dominio]
#
# Exemplos:
#   domain.expira[empresa.com.br]
#   domain.status[empresa.com.br]
#   domain.dns1[empresa.com.br]
#
# Script chamado internamente:
#   /etc/zabbix/scripts/zabbix_domain_monitor.sh <atributo> <dominio>

UserParameter=domain.nome[*],/usr/local/bin/zabbix_domain_monitor.sh nome "$1"
UserParameter=domain.status[*],/usr/local/bin/zabbix_domain_monitor.sh status "$1"
UserParameter=domain.dono[*],/usr/local/bin/zabbix_domain_monitor.sh dono "$1"
UserParameter=domain.donocnpj[*],/usr/local/bin/zabbix_domain_monitor.sh donocnpj "$1"
UserParameter=domain.dononome[*],/usr/local/bin/zabbix_domain_monitor.sh dononome "$1"
UserParameter=domain.pais[*],/usr/local/bin/zabbix_domain_monitor.sh pais "$1"
UserParameter=domain.donoregistro[*],/usr/local/bin/zabbix_domain_monitor.sh donoregistro "$1"
UserParameter=domain.suporteregistro[*],/usr/local/bin/zabbix_domain_monitor.sh suporteregistro "$1"
UserParameter=domain.dns1[*],/usr/local/bin/zabbix_domain_monitor.sh dns1 "$1"
UserParameter=domain.dns2[*],/usr/local/bin/zabbix_domain_monitor.sh dns2 "$1"
UserParameter=domain.dns3[*],/usr/local/bin/zabbix_domain_monitor.sh dns3 "$1"
UserParameter=domain.dns4[*],/usr/local/bin/zabbix_domain_monitor.sh dns4 "$1"
UserParameter=domain.criado[*],/usr/local/bin/zabbix_domain_monitor.sh criado "$1"
UserParameter=domain.criadonumero[*],/usr/local/bin/zabbix_domain_monitor.sh criadonumero "$1"
UserParameter=domain.alterado[*],/usr/local/bin/zabbix_domain_monitor.sh alterado "$1"
UserParameter=domain.expira[*],/usr/local/bin/zabbix_domain_monitor.sh expira "$1"
